### ISSUE TITLE
Consider releasing to Plugin Directory

### ISSUE THREAD

**Issue by kadamwhite** [norcross/airplane-mode#102]
It would be convenient to have this plugin available through the normal WordPress plugin directory, so that it could be trivially installed with WP-CLI, installed via composer using wpackagist, or consumed by any number of other tools which are designed to key off of plugin name slugs within the directory.

**Comment by norcross** [comment]
this is the first valid reason i’ve heard for doing it. i’ll get any existing branches cleaned up and do it.

**Comment by kadamwhite** [comment]
@norcross Anything I could do to help expedite this?

**Comment by norcross** [comment]
come be a parent for a few days? 🤣

jokes aside, i’ll get this submitted today.

**Comment by norcross** [comment]
ok, i finally got it submitted. i'll update the thread when it's approved.

**Comment by norcross** [comment]
is anyone interested in making repo assets for it? (icons / banners)?

**Comment by norcross** [comment]
otherwise, it's in the repo:  https://wordpress.org/plugins/airplane-mode/
