### ISSUE TITLE
Integration with WP Debug Bar

### ISSUE THREAD

**Issue by raisonon** [norcross/airplane-mode#29]
Currently the warning is shown:

WARNING: wp-includes/update.php:457 - An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.)
require_once('wp-admin/admin.php'), do_action('load-themes.php'), call_user_func_array, wp_update_themes, trigger_error

Would be ideal to have this integrated so this doesn't show. As currently if there are other warnings, they could go unnoticed because the Debug will always be lit up as red. Will look into integration. Perhaps as an extension.

Screenshot: https://www.dropbox.com/s/zwg5wowc1ui9ap7/Screenshot%202014-12-10%2013.18.07.png?dl=0

**Comment by norcross** [comment]
I think #30 fixed this issue, can you confirm?

**Comment by norcross** [comment]
I noticed this came up again on my end, albeit a different line ( 295 on `wp-includes/update.php`) so it looks like the update request is still getting passed.

@johnbillion any ideas on where to address this? was thinking maybe `http_request_args` filter was the place but wanted your thoughts.

**Comment by norcross** [comment]
here are some screenshots on my end:

http://cl.ly/image/292x0Z1q1o1b/Image%202015-01-23%20at%209.27.49%20AM.png
http://cl.ly/image/0L0A1Y160J28/Image%202015-01-23%20at%209.27.55%20AM.png

so it looks like various parts of the update logic is being fired at different times.

**Comment by norcross** [comment]
I think we finally solved this.
