### ISSUE TITLE
Number of removed requests

### ISSUE THREAD

**Issue by szepeviktor** [norcross/airplane-mode#38]
Could you add the count of removed HTTP requests into admin bar?

**Comment by norcross** [comment]
doubtful. the calls happen at different times (due to Ajax calls, core calls, and plugins) so there's not a direct sequence to count.

**Comment by szepeviktor** [comment]
I've meant to count at WP_HTTP.

**Comment by norcross** [comment]
I understood that, but to count them would require having them happen in some sort of order, otherwise it would need to store the counts somewhere on a per-page basis. if you want to take a stab at it and write a PR, I'll take a look.

**Comment by szepeviktor** [comment]
Implemented the "stab" https://github.com/norcross/airplane-mode/pulls
