### ISSUE TITLE
How to mute 'Warning: An unexpected error occurred...'?

### ISSUE THREAD

**Issue by szepeviktor** [norcross/airplane-mode#39]
`Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration.`

**Comment by johnbillion** [comment]
This warning is raised directly by WordPress core (in several places) and isn't anything to do with the HTTP API.

Annoying isn't it?

**Comment by szepeviktor** [comment]
I personally think that the Airplane way of disabling HTTP traffic needs refining.
Please steal code from my MU plugin: https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php#L94-L111

**Comment by johnbillion** [comment]
Airplane Mode disables much more than just the update checks.

**Comment by szepeviktor** [comment]
I think the update checks complain: `Warning: An unexpected error occurred...`

**Comment by szepeviktor** [comment]
`with WordPress.org`

**Comment by chriscct7** [comment]
Solved by https://github.com/norcross/airplane-mode/pull/42

**Comment by norcross** [comment]
correct, this is solved.
