### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by szepeviktor** [norcross/airplane-mode#40]
Please consider `wp_add_inline_style( 'wp-admin', $style_string );`

**Comment by norcross** [comment]
do you have a use-case for this? or are you recommending this over loading the CSS file that is currently used?

**Comment by szepeviktor** [comment]
Over loading the current loading.

**Comment by norcross** [comment]
I don't think this is a good fit. `wp_add_inline_style` still requires an enqueue, and the CSS is needed in all three places (front, admin, and login). Other than the additional http request, what is the reasoning behind doing it this way?

**Comment by szepeviktor** [comment]
I wasn't thinking about frontend and login.
On admin it does not need an enqueue because `wp-admin` CSS is always enqueued.
I think think `wp_add_inline_style` is the way of adding inline style in WP.

**Comment by szepeviktor** [comment]
On login there is a hardcoded CSS also.
On the frontend .... there isn't really.

**Comment by johnbillion** [comment]
What does this have to do with Airplane Mode? It doesn't use any inline CSS.

**Comment by szepeviktor** [comment]
Oh sorry!
It must have been another plugin.

**Comment by norcross** [comment]
ahh. that makes more sense. I thought the issue was loading a CSS file itself.
