### ISSUE TITLE
Updates no longer display while Airplane Mode activated and off

### ISSUE THREAD

**Issue by afragen** [norcross/airplane-mode#49]
Updates are hidden while Airplane Mode is activated and off. If I deactivate Airplane Mode the updates now show.

I still have to dig further. Below are some screenshots to explain.

![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/6977016/efe5bc22-d968-11e4-8cdb-2c0010cbaa58.png)
Airplane Mode deactivated.

![screenshot_03](https://cloud.githubusercontent.com/assets/1296790/6977018/f4c0d006-d968-11e4-9569-0418f3e5baa9.png)
Airplane Mode activated and on

![screenshot_04](https://cloud.githubusercontent.com/assets/1296790/6977020/f93add8e-d968-11e4-99a1-aa93fbe282ec.png)
Airplane Mode activated and off

**Comment by norcross** [comment]
i think this is actually due to #44 which I am about to push a fix for

**Comment by norcross** [comment]
about to bump to 0.0.6 across the board to fix this. my bad.
