### ISSUE TITLE
Add Plugins

### ISSUE THREAD

**Issue by szepeviktor** [norcross/airplane-mode#51]
I am very sorry to report that the Add Plugins page is cleaned even when Airplane-Mode is disabled.

**Comment by szepeviktor** [comment]
I think the number of `if ( $this->enabled() )`-s should be reduced.

**Comment by afragen** [comment]
I think the problem here is the last bit of CSS should only be loaded when Airplane Mode is enabled.

**Comment by szepeviktor** [comment]
https://github.com/norcross/airplane-mode/blob/master/airplane-mode.php#L91-L95
is unconditional.

**Comment by szepeviktor** [comment]
These new features shouldn't be executed when Airplane Mode is disabled.

**Comment by afragen** [comment]
I'm working on a patch now

**Comment by afragen** [comment]
#52 should fix this.

**Comment by szepeviktor** [comment]
I think `add_filter( 'install_plugins_tabs', array( $this, 'plugin_add_tabs' ) );` hides the tabs.

**Comment by szepeviktor** [comment]
Please move `if ( $this->enabled() ) {` to line #68

**Comment by norcross** [comment]
@szepeviktor we are addressing this in a different way

**Comment by szepeviktor** [comment]
Thank you. Please close it after your commit.

**Comment by norcross** [comment]
fixed with https://github.com/norcross/airplane-mode/commit/24724297c4f8547703c0950990a31e8e271fa6e1

**Comment by szepeviktor** [comment]
@norcross Sorry, I do not know what this CSS thing is about.
The original issue was that these are excuted when Airplane Mode is disabled:
https://github.com/norcross/airplane-mode/blob/master/airplane-mode.php#L62-L110

**Comment by szepeviktor** [comment]
I was reporting the missing tabs of the Add Plugins page.

**Comment by afragen** [comment]
Does that issue still exist in the current master branch?

**Comment by szepeviktor** [comment]
YEs.

**Comment by afragen** [comment]
A screenshot would be very helpful.

**Comment by szepeviktor** [comment]
Oh! I am very sorry. In the current master everything works.
I just haven't noticed the `if ( ! $this->enabled() )`-s.

Could all these `if`-s move into the constructor?

**Comment by norcross** [comment]
@szepeviktor I have no plans on moving them all to the constructor. since they involve various checks, filters, etc and the plan is for some to have optional setups for user to change status in different ways.
