### ISSUE TITLE
Breaks Dashboard admin menu on Multisite

### ISSUE THREAD

**Issue by johnbillion** [norcross/airplane-mode#65]
When Airplane Mode is enabled on Multisite, the Dashboard admin menu points to `my-sites.php` instead of `index.php`.

Haven't looked into why this is happening yet.

**Comment by afragen** [comment]
Removing or commenting out https://github.com/norcross/airplane-mode/blob/master/airplane-mode.php#L367 fixes the issue. But I'm not quite clear on why it's there in the first place. @norcross will have to provide more insight.

**Comment by norcross** [comment]
found the issue and have a fix coming in the next release.
