### ISSUE TITLE
Don't clear transients when toggling airplane mode

### ISSUE THREAD

**Issue by johnbillion** [norcross/airplane-mode#66]
The [`purge_transients()` method](https://github.com/norcross/airplane-mode/blob/0.0.8/airplane-mode.php#L575-L589) clears the transients for core updates, plugin updates, and theme updates every time the airplane mode status changes.

This means that every time I need to temporarily disable airplane mode, everything is slowed down because the update checks always fire because the transients are always empty.

Clearing these transients serves no purpose, so I think this code should be removed. Thoughts?

**Comment by franz-josef-kaiser** [comment]
Direct link [to the blob](https://github.com/norcross/airplane-mode/blob/de2e0387fd5447bf66d86b9721ff870a265a78d9/airplane-mode.php#L575-L589) for later readers once this gets changed.

**Comment by norcross** [comment]
It would need to happen at least once, to remove any existing pending updates done prior to enabling for the first time. I'm not sure of a way to handle that without doing it each time, but I'm open to ideas.
