### ISSUE TITLE
Don't block local requests

### ISSUE THREAD

**Issue by johnbillion** [norcross/airplane-mode#72]
Airplane Mode blocks all outgoing HTTP requests. It shouldn't block outgoing requests to the current host (for example, requests to `example.dev/wp-cron.php` when you're using `example.dev`) because this host must be accessible due to the fact the user is using the site over this host.

I'll knock up a patch.

**Comment by norcross** [comment]
awesome. this is an issue I wanted to tackle but wasn't sure the best way to handle it. just make sure to include some sort of bypass filter for edge cases where the local call may be calling something else (edge case, I'm sure)

**Comment by norcross** [comment]
fixed via #78
