### ISSUE TITLE
Changes in WP 4.6

### ISSUE THREAD

**Issue by afercia** [norcross/airplane-mode#79]
Hello :) Just wanted to ping you and inform a small is going to land on WP 4.6. Specifically, in the Add Plugin screen, the ".upload" button will behave a bit differently and will have a new CSS class. So if you want to still hide it completely you should use the new CSS class. `upload-view-toggle`

**Comment by norcross** [comment]
thanks! I'll get that updated for sure

**Comment by afercia** [comment]
> a small is going

missed "change" :)
