### ISSUE TITLE
This plugin could hide/deny add new theme button

### ISSUE THREAD

**Issue by onnimonni** [norcross/airplane-mode#83]
Hey!

I'm using whoops errors in my local development. Sometimes the local WordPress can't reach the internet and I'll get warning like this one:

<img width="1637" alt="screen shot 2016-08-25 at 10 19 12 pm" src="https://cloud.githubusercontent.com/assets/5691777/17982751/026a2662-6b12-11e6-9abf-e09464beb492.png">

I want to have these warnings displayed in the frontend so that I can find problems in my code asap. Your plugin seems to solve most of these issues but not this one:

**What I was trying to do:**
When I go to themes folder I can see the **Add new** button.

<img width="926" alt="install-theme-button" src="https://cloud.githubusercontent.com/assets/5691777/17982880/75e703a8-6b12-11e6-9a8f-3d7d479e2920.png">

If I click it all the hooks from this plugin and WordPress create a situation where I'll get error like this one:
<img width="1639" alt="screen shot 2016-08-25 at 10 11 10 pm" src="https://cloud.githubusercontent.com/assets/5691777/17982915/a1a19abc-6b12-11e6-829f-2bc469bb5ba9.png">

**What I wanted to achieve:**

**Add new** button begone:
<img width="761" alt="add-new-button-begone" src="https://cloud.githubusercontent.com/assets/5691777/17983033/3cf2059c-6b13-11e6-8ab0-8ada8b2aa96b.png">

**Comment by norcross** [comment]
I'll review. the "add new theme" can also allow a local upload of a zip file, which we don't want to prevent happening

**Comment by onnimonni** [comment]
I know it does, I just didn't find anything which would disable only the connections to wp.org servers.

Thanks in advance :)!

**Comment by norcross** [comment]
I don't think there is, which is why I'm hiding it via CSS. but I'll look some more.

**Comment by norcross** [comment]
OK. Upon further digging, I was setting items inside the theme API call wrong. I'm making an update that'll fix the error return. There's still a small bit of CSS to load for the page to remove the bar itself (since that can't be moved otherwise)
