### ISSUE TITLE
Helpful Script: Offline Activation

### ISSUE THREAD

**Issue by solepixel** [norcross/airplane-mode#85]
Not an issue/bug, but my internet was out and I was unable to reach the Plugins page of the WordPress admin to activate this plugin due to a fatal error when WordPress was checking for updates. So I threw this together to activate the plugin when you can't get to the Plugins page:

https://gist.github.com/solepixel/e1d03f4dcd1b9e86552b3cc6937325bf

Hope it helps someone else. Thanks!

**Comment by norcross** [comment]
Thanks! I'm still curious as to why it fatal error'd.

**Comment by solepixel** [comment]
Same here. It could have been a non-wordpress.org plugin trying to check for updates, but now that my internet is back up, I can't seem to reproduce it. The only error I could see was this:
https://github.com/WordPress/WordPress/blob/master/wp-includes/update.php#L306, but even with WP_DEBUG set to false, the plugin page was still giving me WSOD. Something else was broken and I gave up looking for it, so just activated Airplane Mode that resolved it.

**Comment by norcross** [comment]
¯\_(ツ)_/¯
