### ISSUE TITLE
PHP 7.2 Deprecated

### ISSUE THREAD

**Issue by geminorum** [norcross/airplane-mode#96]
`PHP Deprecated:  Function create_function() is deprecated in \wp-content\plugins\airplane-mode\airplane-mode.php on line 789`

**Comment by norcross** [comment]
hey @chriscct7 is that function still needed?

**Comment by chriscct7** [comment]
@norcross no it can be removed now it appears

**Comment by norcross** [comment]
this has been fixed in https://github.com/norcross/airplane-mode/releases/tag/0.2.4
