### ISSUE TITLE
Add console notice about blocked scripts

### ISSUE THREAD

**Issue by alpipego** [norcross/airplane-mode#97]
It would be nice to have a console notice whether a script/style has been blocked. I spent an hour debugging before I noticed I had airplane mode on... 

Thoughts?

**Comment by norcross** [comment]
which console? what type of notice?

**Comment by alpipego** [comment]
Browser console. Something along the line of `Airplane Mode blocked script` or the error object that gets added to `src`.

**Comment by norcross** [comment]
I’m curious how this would be implemented. it does show as blocked in the `scripts` portion of Query Monitor

**Comment by alpipego** [comment]
Maybe this is too tightly coupled with Query Monitor. I did not use QM in the project I was working on (and also I was not logged in - otherwise I would've seen that Airplane Mode was on). Implementing the proposed changes in #98 would make this a lot less hacky.

My idea was to gather all blocked scripts, pass their handles/original sources to a late JS and output them.

**Comment by norcross** [comment]
There's a few other utility tools it works with. There just isn't any actual JS output, and I'm hesitant to include any.

based on how the collection is done currently, would including an action on the `block_script_load` and `block_style_load` functions prior to the actual return provide you with what you'd need to extend it?

**Comment by alpipego** [comment]
In order to extend it outside of the plugin, there's no need to add an action.

**Comment by norcross** [comment]
then I don’t see a need to add JS output on top of what’s already there.
